removing onSaveInstance
This commit contains the removal of onSaveInstanceState and OnViewStateRestored methods. After researching and debugging they were the reason for giving the unclear RunTime exception (I don't receive it on my emulator, it only happens on my physical device)
The Error is: Process: com.abdullahalomair.todolist, PID: 28418
 java.lang.StackOverflowError: stack size 8MB